window.STORY = [
  "Mengucap Syukur",
  "Karya: Rara Julia",
  "15 Oktober 2023",
  "Ujian akhir semester telah usai, liburan pun tiba. Bagi Ayudia, liburan adalah hari dimana",
  "untuk bermalas-malasan dengan berlebihan karena membayar energi yang telah terpakai",
  "ketika belajar dan ujian, apalagi ini semester yang sangat berat baginya. Akan tetapi, kali",
  "ini liburan baginya seperti neraka.",
  "“YA NERAKA”.",
  "Isi kepalanya terus berisik bagaikan suara-suara klakson yang tiada henti. Tak hanya itu,",
  "Ayudia sering absen dari makan siang dan makan malam. Dia mengurung diri sambil",
  "menatap langit-langit kamarnya. Ibunya tau karena dia tak mengunci kamarnya, tapi…",
  "akhir-akhir ini dia mengunci kamarnya itu. Dia keluar hanya untuk sarapan.",
  "“Ayu… Ayu… makan lagi nak… Ibu sudah masak ikan kesukaanmu nih… ”",
  "“Kamu sudah 2 hari tidak sarapan… dan hanya di kamar, apa yang kamu lakukan?",
  "Tolong buka kuncinya nak… ”",
  "Mendengar ibunya berbicara dengan lirih, ia membuka pintu kamarnya. Ibunya sedih",
  "melihat anak semata wayangnya itu pucat dan memiliki tatapan kosong. Sebelumnya, Ayu",
  "keluar dengan mata bengkak, tidak tahu apa yang ia tangisi.",
  "“Ayo nak kita makan… ”",
  "Ayudia mematuhi perintah ibunya dan berjalan menuju ruang makan. Lauk kesukaan dia",
  "yang dibuat ibunya sangat harum hingga menyerbak seperti parfum. Sudah lama baginya",
  "tidak makan lauk kesukaan, mungkin terakhir kali 2 tahun lalu. Ayudia makan dengan lahap",
  "agar ibunya tidak bersedih, dia juga menambah porsi, sambil memasak lauk lain, ibu Ayudia",
  "menanyakan mengapa ia akhir-akhir ini mengurung diri, apakah dirinya yang membuat Ayu",
  "sampai begitu, apakah masalah pertemanan, apakah cemas karena nilai ujian akan keluar",
  "atau ada hal yang lain.",
  "“Tidak, tidak di antara semua itu”, saut Ayudia.",
  "“Lalu, jika tidak, alasannya apa? jangan dipendam sendiri, mari saling berbagi”, balas",
  "ibu Ayudia.",
  "Ayudia hanya diam. Ia bingung mau menjelaskan bagaimana. Cukup hanya ia saja yang tau",
  "perasaannya. Ibunya memandang Ayudia dengan heran.",
  "“Gimana kalau Ayudia ikut relawan bareng Altha, tut? kan rame tuh, terus juga pergi",
  "ke desa yang pemandangannya bagus, mungkin mood Ayudia balik lagi. Sekalian dapat",
  "pengalaman”, ujar Devi.",
  "Devi adalah teman dekat ibu Ayudia, mereka berteman sejak sekolah menengah atas",
  "sampai sekarang, mungkin sudah 30 tahun. Astuti, ibu Ayudia bercerita mengenai anak",
  "semata wayangnya itu kepada Devi dan Devi menganjurkan Ayudia ikut relawan. Devi",
  "memiliki komunitas relawan yang sudah amat terkenal dikalangan anak muda dan sudah",
  "berdiri sejak lama. Ia mendirikan bersama suaminya ketika menikah dengan tujuan",
  "mengajak orang-orang membantu pendidikan dan hal lainnya di desa yang jauh",
  "jangkauannya dari kota.",
  "“Apa gapapa Ayudia ikut? dia kan ga ikut seleksi”, balas Astuti.",
  "“Gapapa, mungkin dengan ikut ini mood dia akan balik lagi”, ujar Devi",
  "“Oke baiklah dev, terima kasih telah membantu, akan kubujuk Ayudia”, balas Astuti.",
  "“Oh ya tut, itu berangkatnya senin minggu depan, jadi tolong dikonfirmasikan",
  "langsung jika Ayudia setuju dan kegiatannya berlangsung seminggu di desa Teja”, ungkap",
  "Devi.",
  "“Oke dev, segera kukabarkan”, balas Astuti.",
  "Astuti mengakhiri telepon Devi dan kemudian menuju kamar Ayudia. Kali ini, Ayudia tidak",
  "mengunci pintu kamarnya dan Astuti menengok anaknya itu sedang membaca buku dari",
  "penulis bernama Henry Manampiring.",
  "“Nak, kamu mau ikut relawan ke desa Teja ga? Tante Devi nawarin nih, senin minggu",
  "depan berangkatnya. Kamu pergi bareng anaknya tante Devi si Altha, cuman seminggu",
  "doang kok”, ajak Astuti.",
  "“Tapi kan Ayu ga ikut seleksi. Masak ayu ikut?”, jawab ayu",
  "“Kata tante Devi sih gapapa, dia tiba-tiba kepikiran kamu karena pemandangan",
  "desanya indah dan pasti kamu suka. Jadi, kamu ikut ga? Biar ibu konfirmasi ke tante Devi”",
  "“Hm… ”",
  "“Hm.. Hm.. Mau ga? Lagian kamu 2 bulan liburnya”",
  "“Hm… bareng kak Altha aja ya? Kak Dira ga ikut?”",
  "“Iya, Altha aja”",
  "“Hm… boleh deh… seminggu juga kan?”",
  "“Iya, cuman seminggu Ayudia sayang. Oke, ibu telpon tante Devi dulu”",
  "“Kayaknya seru juga apalagi di desa Teja”, ujar Ayudia.",
  "Kak Altha sebagai ketua koordinator menertibkan mereka dan mengabsen para anggota.",
  "Bus akan berangkat pada jam 8 dan perjalanan menempuh 3 jam ke pusat kota desa Teja,",
  "desa Teja merupakan pulau yang dimana nanti akan menyambung perjalanan",
  "menggunakan kapal dengan waktu tempuh 3 jam.",
  "6 jam perjalanan membuat mereka lelah, kini waktu untuk makan siang. Setelah itu, mereka",
  "akan pergi ke rumah yang telah disewa untuk tempat tinggal mereka. Mereka menyewa 2",
  "rumah, 1 rumah untuk wanita dan 1 lagi untuk laki-laki, walaupun begitu rumah yang",
  "disewa berdekatan. Tak hanya itu, mereka telah mengunjungi kepala desa sebagai memberi",
  "kabar bahwa mereka telah sampai. Kemudian, Ayudia berkenalan dengan salah satu",
  "relawan yang ikut, namanya Dea. Tak disangka Dea masih muda, umurnya 17 tahun, dia",
  "baru lulus SMA dan ikut karena penasaran bagaimana rasanya ikut kegiatan seperti ini.",
  "Mendengar alasan Dea, dia merasa takjub karena dengan usia tergolong muda, dia berniat",
  "hati ingin merasakan kegiatan ini.",
  "Keesokan harinya",
  "Altha, Ayudia, Dea dan 3 lainnya dapat tugas untuk mengajarkan bahasa Inggris di satu",
  "kelas sekolah dasar, dikarenakan di desa belum ada pelajaran bahasa Inggris. Kelas dibuka",
  "oleh Altha, dia banyak mengajar adik-adik dengan nyanyian dari dasar yaitu cara",
  "pengucapan alfabet bahasa Inggris. Kemudian teman lainnya memberi kosakata dasar yang",
  "sering digunakan sehari-hari. Sedangkan, Ayudia mengajak mereka bermain dengan",
  "kosakata bahasa Inggris. Altha melihat Ayudia yang sudah banyak bicara, Altha melihatnya",
  "bagaikan guru muda yang sudah lama tidak bertemu murid-muridnya. Tidak sekedar",
  "bermain games sambil belajar, Ayudia menyiapkan hadiah cemilan bagi siswa-siswi yang",
  "dapat menjawab pertanyaannya.",
  "Di sore hari, mereka bermain bersama anak-anak desa di lapangan. Mereka bermain petak",
  "umpet, lompat tali dan tarik tambang. Ayudia dan teman relawan lainnya juga anak-anak",
  "desa sangat antusias bermain, mereka tidak ingin kalah. Selain itu, ada juga teman relawan",
  "bermain bulutangkis bersama anak-anak desa lainnya dan ada juga bermain sepak bola.",
  "Hari terus berlanjut dengan kegiatan yang sama sampai hari ke empat, mereka",
  "mengunjungi panti asuhan di desa tersebut. Ayudia tak menyangka bahwa disana ada",
  "sebuah panti asuhan. Mereka mengajar anak-anak bahasa Inggris dan membaca kisah Nabi",
  "untuk mereka. Seperti biasa, teman-teman relawan selalu menyelipkan permainan setelah",
  "belajar dan yang banyak menang akan mendapat hadiah. Tidak hanya yang menang, anak",
  "anak panti lainnya juga diberikan buku, makanan dan pakaian. Setelah kegiatan belajar",
  "mengajar selesai, waktu bagi relawan bermain bersama mereka, ada yang bermain sepak",
  "bola, ada yang mewarnai dan ada yang bermain petak umpet. Semantara itu, Ayudia duduk",
  "di pondok kayu di pinggir lapangan sambil melihat para anak-anak panti dan relawan",
  "bermain sepak bola dan Altha yang sedang memotret kegiatan mereka melihat Ayudia dan",
  "menghampirinya, lalu bertanya mengapa ia sebelumnya mengurung diri di kamar dan tak",
  "berbicara apapun kepada ibunya.",
  "“Ah itu… sepertinya ibu bercerita ke tante Devi”",
  "“Ya… Dan mama kakak yang memberi saran untuk mengajak kamu ikut kegiatan ini…",
  "jadi apakah kamu sudah membaik?”",
  "“Jika ditanya sudah membaik atau belum, mungkin setengah karena di pikiran masih",
  "terngiang”",
  "“Maaf, jika aku bicara seperti ini, apa kamu sedang punya masalah bersama",
  "keluarga?”",
  "“Tidak kak”, jawab Ayudia sambil tersenyum dan ia melanjutkan,",
  "“Aku hanya mendengar pembicaraan yang membuat aku berpikir yang tidak-tidak,",
  "aku mendengar tanteku menghadiri pernikahan temannya dan ternyata temannya itu",
  "menikah dengan ayahku, sedangkan dia tidak pernah menemuiku, apakah ia tidak ingat",
  "atau bagaimana?”, ujar Ayudia, kali ini ia berbicara sambil menangis.",
  "Memang sulit jika membicarakan mengenai keluarga. Altha yang tak tega melihat ia",
  "menangis, memeluk Ayudia. Altha tidak tau tau menanggapi seperti apa, ia tidak pernah",
  "merasakan seperti Ayudia, ia hanya bisa memeluk Ayudia dengan harapan Ayudia akan",
  "tenang. Altha tau kalau hal seperti itu tidak mudah diungkapkan apalagi kepada ibunya,",
  "Ayudia nampaknya sudah memendam lama perasaan itu dan mungkin ada yang lain sampai",
  "ia menangis seperti itu.",
  "“Tapi setelah melihat mereka rasanya aku lega karena masih memiliki ibu dan keluarga.",
  "Walaupun begitu, senang bisa melihat mereka tersenyum dan tertawa bersama, mereka",
  "sudah seperti saudara satu sama lain”, ujar Ayudia sambil tersenyum melihat anak-anak",
  "panti bermain sepak bola tepat di hadapannya.",
  "1 hari sebelum kepulangan mereka, mereka mengunjungi air terjun di desa tersebut dan",
  "beberapa pun ada yang berenang.",
  "Keesokannya pun, mereka berpamitan kepada warga desa dan anak-anak, anak-anak yang",
  "mereka ajarkan pun menunggu sampai mereka benar-benar pergi",
  "5 bulan sejak ikut kegiatan relawan tersebut, Ayudia tiap 2 minggu sekali memberi sedekah",
  "ke panti asuhan. Setiap kali dia merasa hal yang dilakukannya buruk dan tak ada",
  "kebahagiaan apapun, ia selalu mengingat bahwa kunci dari semuanya adalah bersyukur."
];

window.STORY_TEXT = window.STORY;
